3/edit notes
graasp/graasp-app-post-it-notes pull request #4
Opened 2021-06-16 13:59 UTC by hagoptaminian

@juancarlosfarah check it out so far. No need for a code review if you're busy but let me know if you have any comments playing around with it. Looks like this:

![Screen Shot 2021-06-16 at 3 58 56 PM](https://user-images.githubusercontent.com/19311953/122232807-cdaff880-cebb-11eb-8d00-68b88fc6cdf5.png)

2021-06-16 15:02 UTC, pyphilia commented
That looks so nice! I played around a bit with it, some minor comments:
- I would change the pointer cursor (when clicking to add a note) with a + sign
- Having a long description triggers a scroll, it would be ideal to be able to resize notes to see everything.

Otherwise really good job!!

2021-06-17 15:53 UTC, juancarlosfarah commented
@hagoptaminian. This looks great! I agree with Kim's first comment. Regarding the second one, I'm not sure. Maybe we can discuss that tomorrow.

👏

2021-06-17 16:01 UTC, juancarlosfarah requested changes
Very nice! Clean code and great first version. Just left some comments and questions in there. Can address here or in future PRs if you've already planned it.

A couple general comments.

1. How about using the different variants of `Typography` instead of changing the font manually? 
2. There's some repeated code, specially in the styling and some minor helper functions. Maybe factor that out.

Otherwise it looks good! Nice job.

2021-06-22 09:24 UTC, hagoptaminian commented on src/components/App.js
> +    // headerVisible: PropTypes.bool.isRequired,
Good catch. Indeed I've opted to go with no header for this application.

2021-06-22 09:24 UTC, hagoptaminian commented on src/components/main/Canvas.js
> +        src="https://images.unsplash.com/photo-1527245592484-dff09c8e4cd9?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1500&q=80"
TBD! For now I left the default as a lightly colored salmon div/background.

2021-06-22 09:25 UTC, hagoptaminian commented on src/components/main/form/FormActions.js
> +    fontSize: '1.1vw',
To make text responsive, I need to use either `vw` or `vh`. I'm choosing the numbers by eyeballing...

2021-06-22 09:27 UTC, hagoptaminian commented
Thanks @pyphilia @juancarlosfarah. Changing the icon to a plus seems to be the way to go. Updating this PR with another (#11) to avoid rebasing.

2021-06-22 09:27 UTC, closed without merging